server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由,uri的协议为lb，表示启用Gateway的负载均衡
      routes:
        - id: payment_routh # payment_route 路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001 # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由

        - id: payment_routh2 # payment_route 路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001 # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/** # 断言，路径相匹配的进行路由
            - After=2020-12-19T13:30:39.260+08:00[Asia/Shanghai] # 时间断言,过了这个时间才能访问
           # - Before=2020-12-19T13:30:39.260+08:00[Asia/Shanghai] # 时间断言,过了这个时间才能访问
           # - Between=2020-12-19T13:30:39.260+08:00[Asia/Shanghai],2020-12-19T13:38:24.379+08:00[Asia/Shanghai] # 时间断言,过了这个时间才能访问
           # - Cookie=username,zzyy #1.jmeter2.postman3.curl --curl http://localhost:9527/payment/lb --cookie "username=zzyy"
           # http://localhost:9527/payment/lb -H "X-Request-ld:123"
           # - Header=X-Request-Id, \d+ # 请求头要有X-Request-Id属性并且值为整数的正则表达式
           # - Host=**.cjw.com
           # - Method=GET
             - Query=username, \d+ # 要有参数名username并且值还要是整数才能路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client:  #服务提供者provider注册进eureka服务列表内
  service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka