server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: git@github.com:Jwchen-bat/endCloud.git #GitHub上面的git仓库名字
          search-paths: ####搜索目录
            - endCloud
       ####读取分支
       label: master
  #rabbitmq相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: cjw
    password: cjw

eureka:
  client:
    service-url:
      defauletZone: http://localhost:7001/eureka
#服务注册到eureka地址



management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: "bus-refresh"
##rabbitmq相关配置，暴露bus刷新配置的端点